name: LawBridge CI

on:
  push:
   branches: [main]
  pull_request:
   branches: [main]

jobs:
  typecheck:
   runs-on: ubuntu-latest

   steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
       node-version: '20'
       cache: 'npm'

    - run: npm ci

    - name: Run type Check
      run: npm run type-check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
        
      - run: npm ci
        
      - name: Run linter
        run: npm run lint

  build:
   needs: [typecheck, lint]
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v4
      
    - uses: actions/setup-node@v4
      with:
       node-version: '20'
       cache: 'npm'

    - run: npm ci 
      
    - name: build
      run: npm run build
      env:
        NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
        NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}
        NEXT_PUBLIC_PAYSTACK_PUBLIC_KEY: ${{ secrets.NEXT_PUBLIC_PAYSTACK_PUBLIC_KEY }}
       